name: Run CI
on:
  push:
    branches:
      - master

jobs:
  run-tests:
    name: Run CI with Node.js ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          npm install
          npm run bootstrap
      - name: Run tests
        run: |
          npm run test
          npm run codecov
